### ISSUE TITLE
Open suggestions when focus on field

### ISSUE THREAD

**Issue by stefanop1** [insolite-dev/field_suggestion#40]
Thanks for this great library.
I am not sure if I missed this. It is possible to open the suggestions list when I go into field?

**Comment by theiskaa** [comment]
**Hello! Yes you definitely can do this:**

You just need two extra properties to test:
`BoxController` and `FocusNode`. Create and give them to your `FieldSuggestion` widget.
```dart
final boxController = BoxController();
final focusNode = FocusNode();
```

Then  initialize a listener for the `focusNode` in initState:
```dart
 focusNode.addListener(() {
      boxController.show!();
      // Also you can do something else here ...
 });
```

If you're using the basic `FieldSuggestion` (I mean without custom builder) it'd open just an empty box the first time.
So, something like that:

<img width="400" alt="Screen Shot 2021-10-10 at 14 58 48" src="https://user-images.githubusercontent.com/59066341/136692776-1892e6b1-780b-46a7-ba53-056059111fc7.png">

So, to avoid this weird behaviour, basically, you can use [custom builder](https://github.com/theiskaa/field_suggestion/wiki/Builder-factory) (that's the best solution). Or do something like that:

Set custom search function to your `FieldSuggestion` widget: 
Which will always keep your box open until you close it.
```dart
customSearch: (_, __) => true,
```

And then convert your `focusNode`'s listener like:
```dart
focusNode.addListener(() {
   boxController.show!();
   textController.text = ' ';
 });
```

The final result would be like that:


https://user-images.githubusercontent.com/59066341/136692890-d2af4810-0de9-4fbb-8a91-1c6c2dad9b01.mov
